libp2p/js-libp2p-daemon

- src/daemon.js
- test/daemon.spec.js
According to the spec and the go implementation of the daemon [libp2p/go-libp2p-daemon/conn.go#L177](https://github.com/libp2p/go-libp2p-daemon/blob/1d7d0a25b6152441e4e8a216d53ee2f7240a161e/conn.go#L177), connect should receive the peerId in bytes and not in b58str
> fix: connect should use peer id in bytes

- src/daemon.js
- test/daemon.spec.js
While `js-libp2p` does not handle this on [libp2p/js-libp2p#323](https://github.com/libp2p/js-libp2p/issues/323), this PR removes the  `/ipfs/{peer_id}` from the multiaddress
> fix: remove ipfs from identify multiaddrs

- src/daemon.js
- src/libp2p.js
- test/daemon/core.spec.js
While `js-libp2p` does not handle this on [libp2p/js-libp2p#323](https://github.com/libp2p/js-libp2p/issues/323), this PR removes the  `/ipfs/{peer_id}` from the multiaddress
> fix: decapsulate ipfs from dht find peer

- package.json
- src/daemon.js
- src/libp2p.js
- src/protocol/index.js
- test/daemon/peerstore.spec.js
- test/protocol.spec.js
This also bumps to the latest release candidate for js-libp2p
Note: the spec for this is still underway and may be subject to change, https://github.com/libp2p/go-libp2p-daemon/pull/91. This is to unblock interop testing with identify in support of the gossipsub needs for peer protocol knowledge.
> feat: add support initial peerstore support

- package.json
- src/libp2p.js
The daemon was pulling `peerInfo` shallowly from the connection instead of calling `getPeerInfo`, which ensures recursive retrieval.
> fix: peer info

- test/daemon/config.spec.js
Fix test for loading Secp256k1 private key, to expect the peer ID to be computed with identity hash, as this is the new behaviour in the peer-id package.
> Fix secp256k1 test

- .travis.yml
- package.json
- src/cli/bin.js
- src/daemon.js
- src/libp2p.js
- test/cli.spec.js
- test/daemon/config.spec.js
- test/daemon/core.spec.js
- test/daemon/peerstore.spec.js
- test/daemon/pubsub.spec.js
- test/daemon/streams.spec.js
- test/util/index.js
Peer store tests had the standard timeout which can cause flakey failures. This bumps the time for node generation.
- Adds node 12 to travis builds
- Updates aegir and fixes linting
> test: bump timeout for peerstore

- README.md
- src/libp2p.js
Added support for specifying the libp2p implementation we want to use in the daemon through an environment variable. This was based on what `ipfsd-ctl` is currently doing.
This allows us to run the interop tests through `js-libp2p` CI.
> feat: specify libp2p dependency through env

- test/daemon/streams.spec.js
There is one test failing because `js-libp2p` peer-info's multiaddrs does not include `/p2p/{peerId}`, which is included on the streamInfo multiaddrs
> chore: update test to encapsulate peer id on multiaddr

- package.json
Tried it locally and it passes interop tests with this new versions which works on node15 (we removed huge bcrypto dep)
> update noise version

- package.json
- src/daemon.js
- src/libp2p.js
Enables DHT by default.  The tests won't pass here until libp2p is released, which needs this module to be released in order for it's tests to pass.
Depends on:
BREAKING CHANGE: The DHT is now enabled by default
> chore: update dht

- .github/dependabot.yml
- package.json
> chore: add dependabot and update engines

- src/cli/bin.js
Starting stopping nodes quickly leads to tests hanging so turn it off by default.
> fix: default nat hole punching to false

- .gitignore
- src/daemon.js
- test/daemon/streams.spec.js
Starting from libp2p 0.36.0, libp2p.handle is async.
https://github.com/libp2p/js-libp2p/releases/tag/v0.36.0
> [Fix] Use await for stream handler registration

- packages/libp2p-daemon-client/README.md
- packages/libp2p-daemon-protocol/README.md
- packages/libp2p-daemon-server/README.md
- packages/libp2p-daemon/README.md
Update docs with new install instructions etc.
Fixes #83
> chore: update docs

- packages/libp2p-daemon-client/package.json
- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-client/test/stream.spec.ts
- packages/libp2p-daemon-protocol/src/stream-handler.ts
- packages/libp2p-daemon-server/src/index.ts
Updates client/server code in line with go implementation to open and read remote streams.
Also updates all deps.
BREAKING CHANGE: the stream type returned by `client.openStream` has changed
> fix!: allow opening remote streams

- packages/libp2p-daemon-protocol/src/index.proto
- packages/libp2p-daemon-protocol/src/index.ts
Updates index.proto to a valid proto3 syntax. Added UNSPECIFIED enum to PeerStoreRequest because enum first value must be 0 which would be breaking change
resolves #66
> fix: fix proto file and generated code

- packages/libp2p-daemon-protocol/src/index.proto
- packages/libp2p-daemon-protocol/src/index.ts
We have to make fields formerly marked "required" in proto2 "optional" in proto3 so a value will always be written onto the wire, even if it's a default value.
> fix: restore proto2 compatibility

- packages/libp2p-daemon-client/package.json
- packages/libp2p-daemon-client/src/dht.ts
- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-client/src/pubsub.ts
Replaces [err-code](https://github.com/IndigoUnited/js-err-code/blob/master/index.js) with [CodeError](https://github.com/libp2p/js-libp2p-interfaces/pull/314)
Related: [js-libp2p#1269](https://github.com/libp2p/js-libp2p/issues/1269)
Changes
- removes err-code from dependencies
- adds @libp2p/interfaces@3.2.0 to dependencies
- uses CodeError in place of err-code
> chore: replace err-code with CodeError

- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-client/src/pubsub.ts
- packages/libp2p-daemon-client/test/pubsub.spec.ts
- packages/libp2p-daemon-server/src/index.ts
- packages/libp2p-daemon-server/src/pubsub.ts
With this implemented we can remove some of the arbitrary delays in the interop tests, instead we can wait until we see the remote node in the topic peer list.
> feat: add get subscribers for pubsub topics

- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-client/src/pubsub.ts
Subscribing to pubsub topics is a two step process - first we subscribe, then we receive messages.
We may subscribe and not receive messages, so change the return type to reflect that.
It now returns a promise, after which is resolved the node is subscribed, and the response has a `messages` method that can be used to iterate over any received messages, and a `cancel` method that will cancel the subscription.
BREAKING CHANGE: the return type of `client.pubsub.subscribe` has changed
> fix!: update pubsub subscribe method to return subscription

- packages/libp2p-daemon-server/src/index.ts
In the upcoming libp2p@2.x release "transient" will change to "limited" so use the newer terminology.
Temporarily uses both config keys to ensure backwards compatibility.
> fix: use "limited" instead of "transient"

- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-protocol/src/upgrader.ts
- packages/libp2p-daemon-server/src/index.ts
Refactors to use the upgrader instead of the handler similar to libp2p.
> fix: use upgrader to get incoming connections

- packages/libp2p-daemon-client/src/index.ts
- packages/libp2p-daemon-server/src/index.ts
> fix: pass abort signal to dial
